services:
  postgres:
    image: postgres:15
    container_name: perdiem_postgres_dev
    environment:
      POSTGRES_DB: perdiem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: perdiem_redis_dev
    ports:
      - "6380:6379"

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile.dev
    container_name: perdiem_backend_dev
    ports:
      - "4001:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/perdiem
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-secret-key-change-in-production
    depends_on:
      - postgres
      - redis
    command: ["pnpm", "run", "dev"]

  frontend:
    build:
      context: .
      dockerfile: web/Dockerfile.dev
    container_name: perdiem_frontend_dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:4001
    depends_on:
      - backend
    command: ["pnpm", "run", "dev"]

volumes:
  postgres_data: